version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: cv-container
    image: cv
    volumes:
      - ./:/app
      - /app/node_modules
#    restart: always
